const SIMILARITY_THRESHOLD = 0.78;

const TEN_MILLISECONDS = 10;

const MAX_POPUP_TEXT_LENGTH = 500;

const PAGE_INPUT_VALIDATION_REGEX = /[0-9]+/;

const POPUP_DISAPPEAR_TIMEOUT = 4000;

export {
  SIMILARITY_THRESHOLD,
  TEN_MILLISECONDS,
  MAX_POPUP_TEXT_LENGTH,
  PAGE_INPUT_VALIDATION_REGEX,
  POPUP_DISAPPEAR_TIMEOUT,
};
