const SIMILARITY_THRESHOLD = 0.78;
const TEN_MILLISECONDS = 10;
const MAX_POPUP_TEXT_LENGTH = 500;
const POPUP_DISAPPEAR_TIMEOUT = 4000;
const PAGE_INPUT_VALIDATION_REGEX = /[0-9]+/;

export {
  SIMILARITY_THRESHOLD,
  MAX_GRAPH_DEPTH,
  MAX_CITATION,
  MAX_REFERENCES,
  MAX_POPUP_TEXT_LENGTH,
  POPUP_DISAPPEAR_TIMEOUT,
  PAGE_INPUT_VALIDATION_REGEX
};
