name: "CD for PDFL chrome extension"

on:
  push:
    branches: [main, PL-146-Browser-Extension]
    paths:
      - browser-extension/**

jobs:
  build-and-deploy-extension:
    name: Build and Deploy the PDFL extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: "zip the extension"
        uses: vimtor/action-zip@v1
        with:
          files: browser-extension/*
          dest: extension.zip

      - name: "publish the extension"
        uses: Klemensas/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.EXTENSION_REFRESH_TOKEN }}
          client-id: ${{ secrets.EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.EXTENSION_CLIENT_SECREWT }}
          file-name: ./extension.zip
          app-id: ${{ secrets.EXTENSION_APP_ID }}
          publish: false
